package tugasakhir.view;

import java.io.File;
import javax.swing.JFileChooser;
import tugasakhir.controller.*;

public class main extends javax.swing.JFrame {
    
    private final JFileChooser openFileChooser;
    rsacrtController rsacrt = new rsacrtController();
    otpController otp = new otpController();
    aveController ave = new aveController();
    Controller ctrl = new Controller();
    
    public main() {
        initComponents();
        openFileChooser = new JFileChooser();
        openFileChooser.setCurrentDirectory(new File("d://temp"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel39 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filePath = new javax.swing.JTextField();
        browseMsgEnc_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        show_Plaintext = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        show_Cyphertext = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        text_Length = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        encryptText_Button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        importPublicKey_Button = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        show_PubKeyE = new javax.swing.JTextField();
        show_PubKeyN = new javax.swing.JTextField();
        encryptKey_Button = new javax.swing.JButton();
        saveCypherkey_Button = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        otp_Key = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        show_Plainkey = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        show_Cipherkey = new javax.swing.JTextArea();
        saveCyphertext_Button = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        Encrypttxt_Time = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Encryptkey_Time = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        importPrivateKey_Button = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        show_PrvKeyp = new javax.swing.JTextField();
        show_PrvKeyq = new javax.swing.JTextField();
        decryptKey_Button = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        cyphertextPath = new javax.swing.JTextField();
        browseMsgDec_Button = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        show_Cyphertext2 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        show_Plaintext2 = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        decryptText_Button = new javax.swing.JButton();
        savePTextResult_Button = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        show_Plainkey2 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        show_Cipherkey2 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        otp_KeyDec = new javax.swing.JTextArea();
        cypherkeyPath = new javax.swing.JTextField();
        browsekeyDec_Button = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        decryptkey_Time = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        decrypttxt_Time = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        show_PrvKeydp = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        show_PrvKeydq = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        show_PrvKeyqInv = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        AvEPath = new javax.swing.JTextField();
        browseMsgAve_button = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        plntxt_show = new javax.swing.JTextArea();
        encryptAve_Button = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        cptxt_show = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        cptxtmod_show = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        avalancheEffect_show = new javax.swing.JTextField();
        diffBit_show = new javax.swing.JTextField();
        totalBit_show = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        show_PubKeyE1 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        show_PubKeyN1 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        plntxtmod_show = new javax.swing.JTextArea();
        importPubKeyAvE_Button = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        Ave_Button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        randomPrimep = new javax.swing.JTextField();
        randomPrimeq = new javax.swing.JTextField();
        randomPrime_Button = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        variableN_show = new javax.swing.JTextField();
        variableE_show = new javax.swing.JTextField();
        variableD_show = new javax.swing.JTextField();
        generateKey_Button = new javax.swing.JButton();
        variableDp_show = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        variableDq_show = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        variableqInv_show = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();

        jLabel39.setText("Public Key (e)");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Encrypt Message");

        browseMsgEnc_button.setText("Browse");
        browseMsgEnc_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseMsgEnc_buttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Plaintext");

        show_Plaintext.setColumns(20);
        show_Plaintext.setRows(5);
        jScrollPane1.setViewportView(show_Plaintext);

        jLabel3.setText("Ciphertext");

        show_Cyphertext.setColumns(20);
        show_Cyphertext.setRows(5);
        jScrollPane2.setViewportView(show_Cyphertext);

        jLabel4.setText("Length:");

        jLabel5.setText("OTP Key:");

        encryptText_Button.setText("Encrypt");
        encryptText_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptText_ButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Encrypt Key");

        jLabel7.setText("OTP");

        jLabel8.setText("Cypherkey");

        importPublicKey_Button.setText("Import Public Key");
        importPublicKey_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importPublicKey_ButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Public Key (e)");

        jLabel10.setText("Public Key (N)");

        encryptKey_Button.setText("Encrypt");
        encryptKey_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptKey_ButtonActionPerformed(evt);
            }
        });

        saveCypherkey_Button.setText("Save");
        saveCypherkey_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCypherkey_ButtonActionPerformed(evt);
            }
        });

        otp_Key.setColumns(20);
        otp_Key.setRows(5);
        jScrollPane5.setViewportView(otp_Key);

        show_Plainkey.setColumns(20);
        show_Plainkey.setRows(5);
        jScrollPane6.setViewportView(show_Plainkey);

        show_Cipherkey.setColumns(20);
        show_Cipherkey.setRows(5);
        jScrollPane7.setViewportView(show_Cipherkey);

        saveCyphertext_Button.setText("Save");
        saveCyphertext_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCyphertext_ButtonActionPerformed(evt);
            }
        });

        jLabel26.setText("Running Time:");

        jLabel27.setText("Running Time:");

        jLabel30.setText("Input Public key: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(show_PubKeyE, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel27)
                                                .addGap(19, 19, 19))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel30)
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(importPublicKey_Button)
                                            .addComponent(Encryptkey_Time)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(encryptKey_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveCypherkey_Button))
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(19, 19, 19)
                                        .addComponent(Encrypttxt_Time))
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(filePath, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(browseMsgEnc_button))
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(19, 19, 19)
                                        .addComponent(text_Length, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 67, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane5))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 442, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(3, 3, 3)
                                .addComponent(show_PubKeyN, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(encryptText_Button)
                .addGap(18, 18, 18)
                .addComponent(saveCyphertext_Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseMsgEnc_button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(text_Length, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(Encrypttxt_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encryptText_Button)
                    .addComponent(saveCyphertext_Button))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(show_PubKeyE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(show_PubKeyN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(Encryptkey_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(encryptKey_Button)
                        .addComponent(saveCypherkey_Button))
                    .addComponent(importPublicKey_Button)
                    .addComponent(jLabel30))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Enkripsi", jPanel1);

        jLabel11.setText("Decrypt Key");

        jLabel12.setText("Cypherkey OTP");

        jLabel13.setText("Plainkey OTP");

        importPrivateKey_Button.setText("Import Private Key");
        importPrivateKey_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importPrivateKey_ButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("Private Key (p)");

        jLabel15.setText("Private Key (q)");

        show_PrvKeyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_PrvKeypActionPerformed(evt);
            }
        });

        decryptKey_Button.setText("Decrypt");
        decryptKey_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptKey_ButtonActionPerformed(evt);
            }
        });

        jLabel16.setText("Decrypt Message");

        browseMsgDec_Button.setText("Browse");
        browseMsgDec_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseMsgDec_ButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("Cyphertext");

        show_Cyphertext2.setColumns(20);
        show_Cyphertext2.setRows(5);
        jScrollPane3.setViewportView(show_Cyphertext2);

        jLabel18.setText("Plaintext");

        show_Plaintext2.setColumns(20);
        show_Plaintext2.setRows(5);
        jScrollPane4.setViewportView(show_Plaintext2);

        jLabel19.setText("OTP Key");

        decryptText_Button.setText("Decrypt");
        decryptText_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptText_ButtonActionPerformed(evt);
            }
        });

        savePTextResult_Button.setText("Save");
        savePTextResult_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePTextResult_ButtonActionPerformed(evt);
            }
        });

        show_Plainkey2.setColumns(20);
        show_Plainkey2.setRows(5);
        jScrollPane8.setViewportView(show_Plainkey2);

        show_Cipherkey2.setColumns(20);
        show_Cipherkey2.setRows(5);
        jScrollPane9.setViewportView(show_Cipherkey2);

        otp_KeyDec.setColumns(20);
        otp_KeyDec.setRows(5);
        jScrollPane10.setViewportView(otp_KeyDec);

        browsekeyDec_Button.setText("Browse");
        browsekeyDec_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsekeyDec_ButtonActionPerformed(evt);
            }
        });

        jLabel28.setText("Running Time:");

        jLabel29.setText("Running Time:");

        jLabel32.setText("Import Private Key: ");

        jLabel46.setText("Private Key (dp)");

        jLabel47.setText("Private Key (dq)");

        jLabel48.setText("Private Key (qInv)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12))
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(show_PrvKeyq, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(show_PrvKeyp, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(show_PrvKeydp, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(show_PrvKeydq, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(importPrivateKey_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 460, Short.MAX_VALUE)
                        .addComponent(decryptKey_Button))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(show_PrvKeyqInv, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decryptkey_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane10))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel29)
                                    .addGap(18, 18, 18)
                                    .addComponent(decrypttxt_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(decryptText_Button)
                                .addGap(18, 18, 18)
                                .addComponent(savePTextResult_Button))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cypherkeyPath, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(browsekeyDec_Button))
                            .addComponent(jLabel16)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cyphertextPath, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(browseMsgDec_Button)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cypherkeyPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browsekeyDec_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(64, 64, 64))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(show_PrvKeyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(show_PrvKeyq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(show_PrvKeydp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47)
                    .addComponent(show_PrvKeydq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(show_PrvKeyqInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(importPrivateKey_Button)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(decryptkey_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(decryptKey_Button)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cyphertextPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseMsgDec_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(decrypttxt_Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(decryptText_Button)
                            .addComponent(savePTextResult_Button))))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dekripsi", jPanel2);

        jLabel31.setText("Avalanche Effect");

        browseMsgAve_button.setText("Browse");
        browseMsgAve_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseMsgAve_buttonActionPerformed(evt);
            }
        });

        plntxt_show.setColumns(20);
        plntxt_show.setRows(5);
        jScrollPane11.setViewportView(plntxt_show);

        encryptAve_Button.setText("Encrypt");
        encryptAve_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptAve_ButtonActionPerformed(evt);
            }
        });

        jLabel34.setText("Cipherteks 1");

        jLabel35.setText("Cipherteks 2");

        cptxt_show.setColumns(20);
        cptxt_show.setRows(5);
        jScrollPane14.setViewportView(cptxt_show);

        cptxtmod_show.setColumns(20);
        cptxtmod_show.setRows(5);
        jScrollPane15.setViewportView(cptxtmod_show);

        jLabel36.setText("Total bit: ");

        jLabel37.setText("Perubahan bit: ");

        jLabel38.setText("Avalanche Effect: ");

        jLabel40.setText("Public Key (e)");

        jLabel41.setText("Public Key (N)");

        jLabel42.setText("Plaintext");

        plntxtmod_show.setColumns(20);
        plntxtmod_show.setRows(5);
        jScrollPane12.setViewportView(plntxtmod_show);

        importPubKeyAvE_Button.setText("Import Public Key");
        importPubKeyAvE_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importPubKeyAvE_ButtonActionPerformed(evt);
            }
        });

        jLabel43.setText("Modified Plaintext");

        Ave_Button.setText("Avalanche Effect");
        Ave_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ave_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(importPubKeyAvE_Button)
                        .addGap(18, 18, 18)
                        .addComponent(encryptAve_Button))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(show_PubKeyE1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(show_PubKeyN1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(AvEPath, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(browseMsgAve_button))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(diffBit_show, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(avalancheEffect_show, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel34)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addGap(308, 308, 308))
                                    .addComponent(jScrollPane15)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel37))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(334, 334, 334)
                                        .addComponent(jLabel43))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(totalBit_show, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Ave_Button)))))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AvEPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseMsgAve_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(show_PubKeyE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(show_PubKeyN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encryptAve_Button)
                    .addComponent(importPubKeyAvE_Button))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalBit_show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Ave_Button)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(diffBit_show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(avalancheEffect_show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Avalanche Effect", jPanel4);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Bilangan Prima Acak");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("p:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setText("q:");

        randomPrime_Button.setText("Random");
        randomPrime_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomPrime_ButtonActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel23.setText("E:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel24.setText("N:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel25.setText("D:");

        generateKey_Button.setText("Generate");
        generateKey_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateKey_ButtonActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel33.setText("Dp:");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel44.setText("Dq:");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel45.setText("qInv:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(randomPrimep, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(randomPrimeq, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(randomPrime_Button))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(18, 18, 18)
                                        .addComponent(variableD_show, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addGap(18, 18, 18)
                                        .addComponent(variableDp_show, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel44)
                                    .addGap(18, 18, 18)
                                    .addComponent(variableDq_show, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addGap(18, 18, 18)
                                .addComponent(variableqInv_show, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(variableE_show, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addGap(18, 18, 18)
                                    .addComponent(variableN_show, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(generateKey_Button)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(randomPrimep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(randomPrimeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(randomPrime_Button)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(variableN_show, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(variableE_show, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(variableD_show, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(variableDp_show, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addComponent(variableDq_show, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addComponent(variableqInv_show, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(generateKey_Button)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Generate Key", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseMsgEnc_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseMsgEnc_buttonActionPerformed
        int returnValue = openFileChooser.showOpenDialog(this);
        
        if(returnValue == JFileChooser.APPROVE_OPTION){
            File F = openFileChooser.getSelectedFile();
            String path = F.getAbsolutePath();
            
            otp.setPlaintext(ctrl.displayContent(path));
            otp.setOTPKeyLength(otp.getPlaintext().length());
            
            filePath.setText(path);
            show_Plaintext.setText(otp.getPlaintext());
            text_Length.setText("" + otp.getOTPKeyLength());
        } else {
            filePath.setText("No File Choosen!");
        }
    }//GEN-LAST:event_browseMsgEnc_buttonActionPerformed

    private void randomPrime_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomPrime_ButtonActionPerformed
        rsacrt.setpRandomVal(ctrl.randomPrimeP());
        rsacrt.setqRandomVal(ctrl.randomPrimeQ());
        
        randomPrimep.setText("" + rsacrt.getpRandomVal());
        randomPrimeq.setText("" + rsacrt.getqRandomVal());
    }//GEN-LAST:event_randomPrime_ButtonActionPerformed

    private void generateKey_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateKey_ButtonActionPerformed
        rsacrt.setnVal(rsacrt.generateKeyNRSACRT(rsacrt.getpRandomVal(), rsacrt.getqRandomVal()));
        rsacrt.seteVal(rsacrt.generateKeyERSACRT());
        rsacrt.setdVal(rsacrt.generateKeyDRSACRT(rsacrt.getpRandomVal(), rsacrt.getqRandomVal(), rsacrt.geteVal(), rsacrt.getnVal()));
        rsacrt.setDpVal(rsacrt.generateKeydpRSACRT(rsacrt.getpRandomVal(), rsacrt.geteVal()));
        rsacrt.setDqVal(rsacrt.generateKeydpRSACRT(rsacrt.getqRandomVal(), rsacrt.geteVal()));
        rsacrt.setqInvVal(rsacrt.generateKeyqInvRSACRT(rsacrt.getpRandomVal(), rsacrt.getqRandomVal()));
        
        variableN_show.setText("" + rsacrt.getnVal());
        variableE_show.setText("" + rsacrt.geteVal());
        variableD_show.setText("" + rsacrt.getdVal());
        variableDp_show.setText("" + rsacrt.getDpVal());
        variableDq_show.setText("" + rsacrt.getDqVal());
        variableqInv_show.setText("" + rsacrt.getqInvVal());
    }//GEN-LAST:event_generateKey_ButtonActionPerformed

    private void encryptKey_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptKey_ButtonActionPerformed
        double startTime = ctrl.getEncStartTime();
       
        rsacrt.setCyphertext(rsacrt.encrypt(otp.getOtpKey(), rsacrt.getnVal(), rsacrt.geteVal()));
        
        double endTime = ctrl.getEncEndTime();
        
        Encryptkey_Time.setText(ctrl.countRunningTime(startTime, endTime) + " Ms");
        show_Cipherkey.setText(rsacrt.getCyphertext());
    }//GEN-LAST:event_encryptKey_ButtonActionPerformed

    private void encryptText_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptText_ButtonActionPerformed
        otp.setOtpKey(otp.generateOTPKey(otp.getOTPKeyLength()));
        otp.saveUsedKey(otp.getOtpKey());
        
        double startTime = ctrl.getEncStartTime();
        
        otp.setCyphertext(otp.encrypt(otp.getPlaintext(), otp.getOtpKey()));
        
        double endTime = ctrl.getEncEndTime();
        
        otp_Key.setText(otp.getOtpKey());
        show_Plainkey.setText(otp.getOtpKey());
        Encrypttxt_Time.setText(ctrl.countRunningTime(startTime, endTime) + " Ms");
        show_Cyphertext.setText(otp.getCyphertext());
    }//GEN-LAST:event_encryptText_ButtonActionPerformed

    private void importPublicKey_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importPublicKey_ButtonActionPerformed
        show_PubKeyE.setText("" + rsacrt.geteVal());
        show_PubKeyN.setText("" + rsacrt.getnVal());
    }//GEN-LAST:event_importPublicKey_ButtonActionPerformed

    private void decryptText_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptText_ButtonActionPerformed
        double startTime = ctrl.getEncStartTime();
        
        otp.setPlaintextdec(otp.decrypt(otp.getBrwscyphertext(), otp.getOtpkeydec()));

        double endTime = ctrl.getEncEndTime();
        
        decrypttxt_Time.setText(ctrl.countRunningTime(startTime, endTime) + " Ms");
        show_Plaintext2.setText(otp.getPlaintextdec());
    }//GEN-LAST:event_decryptText_ButtonActionPerformed

    private void browseMsgDec_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseMsgDec_ButtonActionPerformed
        int returnValue = openFileChooser.showOpenDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            File F = openFileChooser.getSelectedFile();
            String path = F.getAbsolutePath();
            
            otp.setBrwscyphertext(ctrl.displayContent(path));
            
            cyphertextPath.setText(path);
            show_Cyphertext2.setText(otp.getBrwscyphertext());
        } else {
            filePath.setText("No File Choosen!");
        }
    }//GEN-LAST:event_browseMsgDec_ButtonActionPerformed

    private void decryptKey_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptKey_ButtonActionPerformed
        double startTime = ctrl.getEncStartTime();
        
        otp.setOtpkeydec(rsacrt.decrypt(rsacrt.getBrwscyphertext(), rsacrt.getpRandomVal(), rsacrt.getqRandomVal(), rsacrt.getDpVal(), rsacrt.getDqVal(), rsacrt.getqInvVal()));
        
        double endTime = ctrl.getEncEndTime();
        decryptkey_Time.setText(ctrl.countRunningTime(startTime, endTime) + " Ms");
        
        show_Plainkey2.setText(otp.getOtpkeydec());
        otp_KeyDec.setText(otp.getOtpkeydec());
    }//GEN-LAST:event_decryptKey_ButtonActionPerformed

    private void importPrivateKey_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importPrivateKey_ButtonActionPerformed
        show_PrvKeyp.setText("" + rsacrt.getpRandomVal());
        show_PrvKeyq.setText("" + rsacrt.getqRandomVal());
        show_PrvKeydp.setText("" + rsacrt.getDpVal());
        show_PrvKeydq.setText("" + rsacrt.getDqVal());
        show_PrvKeyqInv.setText("" + rsacrt.getqInvVal());
    }//GEN-LAST:event_importPrivateKey_ButtonActionPerformed

    private void browsekeyDec_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsekeyDec_ButtonActionPerformed
        int returnValue = openFileChooser.showOpenDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            File F = openFileChooser.getSelectedFile();
            String path = F.getAbsolutePath();
            
            rsacrt.setBrwscyphertext(ctrl.displayKey(path));
            
            cypherkeyPath.setText(path);
            show_Cipherkey2.setText(rsacrt.getBrwscyphertext());
        } else {
            filePath.setText("No File Choosen!");
        }
    }//GEN-LAST:event_browsekeyDec_ButtonActionPerformed

    private void saveCyphertext_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCyphertext_ButtonActionPerformed
        ctrl.saveCyphertext(otp.getCyphertext());
    }//GEN-LAST:event_saveCyphertext_ButtonActionPerformed

    private void saveCypherkey_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCypherkey_ButtonActionPerformed
        ctrl.saveCypherkey(rsacrt.getCyphertext());
    }//GEN-LAST:event_saveCypherkey_ButtonActionPerformed

    private void savePTextResult_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePTextResult_ButtonActionPerformed
        ctrl.saveptResult(otp.getPlaintextdec());
    }//GEN-LAST:event_savePTextResult_ButtonActionPerformed

    private void browseMsgAve_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseMsgAve_buttonActionPerformed
        int returnValue = openFileChooser.showOpenDialog(this);
        if(returnValue == JFileChooser.APPROVE_OPTION){
            File F = openFileChooser.getSelectedFile();
            String path = F.getAbsolutePath();
            
            ave.setPlaintextave(ctrl.displayContent(path));
            ave.setPlaintextavemod(ctrl.modPlaintxt(ave.getPlaintextave()));
            
            AvEPath.setText(path);
            plntxt_show.setText(ave.getPlaintextave());
            plntxtmod_show.setText(ave.getPlaintextavemod());
            
        } else {
            AvEPath.setText("No File Choosen!");
        }
    }//GEN-LAST:event_browseMsgAve_buttonActionPerformed

    private void encryptAve_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptAve_ButtonActionPerformed
        ave.setCyphertextave(rsacrt.encrypt(ave.getPlaintextave(), rsacrt.getnVal(), rsacrt.geteVal()));
        ave.setCyphertextavemod(rsacrt.encrypt(ave.getPlaintextavemod(), rsacrt.getnVal(), rsacrt.geteVal()));
        
        cptxt_show.setText(ave.getCyphertextave());
        cptxtmod_show.setText(ave.getCyphertextavemod());
        totalBit_show.setText("" + ave.countBit(ave.getCyphertextave(), ave.getCyphertextavemod()));
        diffBit_show.setText("" + ave.diffBit(ave.getCyphertextave(), ave.getCyphertextavemod()));
        avalancheEffect_show.setText("" + ave.hitungAvalanche(ave.getCyphertextave(), ave.getCyphertextavemod()));
    }//GEN-LAST:event_encryptAve_ButtonActionPerformed

    private void importPubKeyAvE_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importPubKeyAvE_ButtonActionPerformed
        show_PubKeyE1.setText("" + rsacrt.geteVal());
        show_PubKeyN1.setText("" + rsacrt.getnVal());
    }//GEN-LAST:event_importPubKeyAvE_ButtonActionPerformed

    private void show_PrvKeypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_PrvKeypActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_show_PrvKeypActionPerformed

    private void Ave_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ave_ButtonActionPerformed
        totalBit_show.setText("" + ave.countBit(cptxt_show.getText(), cptxtmod_show.getText()));
        diffBit_show.setText("" + ave.diffBit(cptxt_show.getText(), cptxtmod_show.getText()));
        avalancheEffect_show.setText("" + ave.hitungAvalanche(cptxt_show.getText(), cptxtmod_show.getText()));
    }//GEN-LAST:event_Ave_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            main main = new main();
            main.setVisible(true);
            main.setLocationRelativeTo(null);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AvEPath;
    private javax.swing.JButton Ave_Button;
    private javax.swing.JTextField Encryptkey_Time;
    private javax.swing.JTextField Encrypttxt_Time;
    private javax.swing.JTextField avalancheEffect_show;
    private javax.swing.JButton browseMsgAve_button;
    private javax.swing.JButton browseMsgDec_Button;
    private javax.swing.JButton browseMsgEnc_button;
    private javax.swing.JButton browsekeyDec_Button;
    private javax.swing.JTextArea cptxt_show;
    private javax.swing.JTextArea cptxtmod_show;
    private javax.swing.JTextField cypherkeyPath;
    private javax.swing.JTextField cyphertextPath;
    private javax.swing.JButton decryptKey_Button;
    private javax.swing.JButton decryptText_Button;
    private javax.swing.JTextField decryptkey_Time;
    private javax.swing.JTextField decrypttxt_Time;
    private javax.swing.JTextField diffBit_show;
    private javax.swing.JButton encryptAve_Button;
    private javax.swing.JButton encryptKey_Button;
    private javax.swing.JButton encryptText_Button;
    private javax.swing.JTextField filePath;
    private javax.swing.JButton generateKey_Button;
    private javax.swing.JButton importPrivateKey_Button;
    private javax.swing.JButton importPubKeyAvE_Button;
    private javax.swing.JButton importPublicKey_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea otp_Key;
    private javax.swing.JTextArea otp_KeyDec;
    private javax.swing.JTextArea plntxt_show;
    private javax.swing.JTextArea plntxtmod_show;
    private javax.swing.JButton randomPrime_Button;
    private javax.swing.JTextField randomPrimep;
    private javax.swing.JTextField randomPrimeq;
    private javax.swing.JButton saveCypherkey_Button;
    private javax.swing.JButton saveCyphertext_Button;
    private javax.swing.JButton savePTextResult_Button;
    private javax.swing.JTextArea show_Cipherkey;
    private javax.swing.JTextArea show_Cipherkey2;
    private javax.swing.JTextArea show_Cyphertext;
    private javax.swing.JTextArea show_Cyphertext2;
    private javax.swing.JTextArea show_Plainkey;
    private javax.swing.JTextArea show_Plainkey2;
    private javax.swing.JTextArea show_Plaintext;
    private javax.swing.JTextArea show_Plaintext2;
    private javax.swing.JTextField show_PrvKeydp;
    private javax.swing.JTextField show_PrvKeydq;
    private javax.swing.JTextField show_PrvKeyp;
    private javax.swing.JTextField show_PrvKeyq;
    private javax.swing.JTextField show_PrvKeyqInv;
    private javax.swing.JTextField show_PubKeyE;
    private javax.swing.JTextField show_PubKeyE1;
    private javax.swing.JTextField show_PubKeyN;
    private javax.swing.JTextField show_PubKeyN1;
    private javax.swing.JTextField text_Length;
    private javax.swing.JTextField totalBit_show;
    private javax.swing.JTextField variableD_show;
    private javax.swing.JTextField variableDp_show;
    private javax.swing.JTextField variableDq_show;
    private javax.swing.JTextField variableE_show;
    private javax.swing.JTextField variableN_show;
    private javax.swing.JTextField variableqInv_show;
    // End of variables declaration//GEN-END:variables
}
